// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmd72guK7rgRij0pNlTCnftRq7pqizTZ0',
    appId: '1:814668586759:web:8092f5b7487f68f5402fa2',
    messagingSenderId: '814668586759',
    projectId: 'fir-auth-fa221',
    authDomain: 'fir-auth-fa221.firebaseapp.com',
    storageBucket: 'fir-auth-fa221.firebasestorage.app',
    measurementId: 'G-F9K286T0CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7rmtt0FkH5YkaAv4BL1hs1dss01TUv5g',
    appId: '1:814668586759:android:b0ad8027b6a1ce62402fa2',
    messagingSenderId: '814668586759',
    projectId: 'fir-auth-fa221',
    storageBucket: 'fir-auth-fa221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhXg00UQG9hoS0QuxSH80n76QfyK4REdc',
    appId: '1:814668586759:ios:e27ae9bf2e6d6120402fa2',
    messagingSenderId: '814668586759',
    projectId: 'fir-auth-fa221',
    storageBucket: 'fir-auth-fa221.firebasestorage.app',
    iosBundleId: 'com.example.blocAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhXg00UQG9hoS0QuxSH80n76QfyK4REdc',
    appId: '1:814668586759:ios:e27ae9bf2e6d6120402fa2',
    messagingSenderId: '814668586759',
    projectId: 'fir-auth-fa221',
    storageBucket: 'fir-auth-fa221.firebasestorage.app',
    iosBundleId: 'com.example.blocAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmd72guK7rgRij0pNlTCnftRq7pqizTZ0',
    appId: '1:814668586759:web:5deb4a4f34eb866c402fa2',
    messagingSenderId: '814668586759',
    projectId: 'fir-auth-fa221',
    authDomain: 'fir-auth-fa221.firebaseapp.com',
    storageBucket: 'fir-auth-fa221.firebasestorage.app',
    measurementId: 'G-X9HRLQ45KW',
  );
}
